export const STATUS = {
  IDLE: 'IDLE',
  SUBMISSION_DETECTED: 'SUBMISSION_DETECTED',
  CHECKING_SUBMISSION: 'CHECKING_SUBMISSION',
  ACCEPTED: 'ACCEPTED',
  NOT_ACCEPTED: 'NOT_ACCEPTED',
  CAPTURING_CODE: 'CAPTURING_CODE',
  GENERATING_README: 'GENERATING_README',
  README_GENERATED: 'README_GENERATED',
  PUSHING_TO_GITHUB: 'PUSHING_TO_GITHUB',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  DUPLICATE: 'DUPLICATE',
};

export const MESSAGE_TYPES = {
  LEETCODE_SUBMISSION_ACCEPTED: 'LEETCODE_SUBMISSION_ACCEPTED',
  LEETCODE_SUBMISSION_REJECTED: 'LEETCODE_SUBMISSION_REJECTED',
  LEETCODE_PAGE_UPDATED: 'LEETCODE_PAGE_UPDATED',
  STATUS_UPDATE: 'STATUS_UPDATE',
  TRIGGER_PUSH: 'TRIGGER_PUSH',
  GET_STATUS: 'GET_STATUS',
};

export const STORAGE_KEYS = {
  GITHUB_TOKEN: 'github_token',
  GITHUB_USER: 'github_user',
  SELECTED_REPO: 'selected_repo',
  PROCESSED_SUBMISSIONS: 'processed_submissions',
  USER_PREFERENCES: 'user_preferences',
  RECENT_ACTIVITY: 'recent_activity',
  BACKEND_URL: 'backend_url',
  CACHED_README: 'cached_readme',
};

export const DEFAULT_BACKEND_URL = 'http://localhost:5000';
